env                    = "dev-uat"
region                 = "ap-southeast-1"
name_prefix            = "ce10grp2"
eks_node_instance_type = "t3.medium"
eks_node_min_size      = 3
eks_node_max_size      = 3
eks_node_desired_size  = 3
eks_admin_users        = ["torwei.goh", "leoeric", "zacharykwek15", "mpatra93"]
eks_developer_users    = ["aliasgharsh53"]
eks_allowed_namespaces = ["ce10grp2-dev", "ce10grp2-uat"]
app_api_ecr_name       = "ce10grp2-app/api"
app_frontend_ecr_name  = "ce10grp2-app/frontend"