configs:
  params:
    server.insecure: "true"
server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      external-dns.alpha.kubernetes.io/hostname: "argocd-dev-uat.ce10grp2.sctp-sandbox.com"
    ingressClassName: "nginx"
    hostname: "argocd-dev-uat.ce10grp2.sctp-sandbox.com"