name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        options:
        - dev-uat
        - prod

permissions:
  id-token: write
  contents: read
  
env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  terraform-deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: github-run-id-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Deploy ECR
        working-directory: ./ecr
        run: |
          terraform init
          terraform workspace select -or-create ${{ github.event.inputs.environment }}
          terraform workspace list
          terraform validate
          terraform plan -var-file=env/${{ github.event.inputs.environment }}.tfvars
          terraform apply -var-file=env/${{ github.event.inputs.environment }}.tfvars --auto-approve

      - name: Deploy EKS
        working-directory: ./eks
        run: |
          terraform init
          terraform workspace select -or-create ${{ github.event.inputs.environment }}
          terraform workspace list
          terraform validate
          terraform plan -var-file=env/${{ github.event.inputs.environment }}.tfvars
          terraform apply -var-file=env/${{ github.event.inputs.environment }}.tfvars --auto-approve

      - name: Capture EKS Outputs
        working-directory: ./eks
        run: |
          echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> $GITHUB_ENV
          echo "CLUSTER_ENDPOINT=$(terraform output -raw cluster_endpoint)" >> $GITHUB_ENV

      - name: Setup Kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: Setup Cluster Configs
        run: |
          echo "Applying StorageClass manifest..."
          kubectl apply -f ./k8s/cluster-configs/storageclass.yaml