name: Deploy EKS Cluster

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        options:
          - dev
          - uat
          - prod

env:
  AWS_REGION: ap-southeast-1

jobs:
  terraform-create-eks-cluster:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./eks

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: github-run-id-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Workspace
        run: |
          terraform workspace select -or-create ${{ github.event.inputs.environment }}
          terraform workspace list

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=${{ github.event.inputs.environment }}.tfvars

      - name: Terraform Apply
        run: terraform apply -var-file=${{ github.event.inputs.environment }}.tfvars --auto-approve

      # --- upgrade storage class from v2 to v3 ---
      - name: Apply Kubernetes Manifests
        run: |
          # The cluster_name variable should match what is defined in your .tfvars file
          CLUSTER_NAME=$(grep 'cluster_name' ${{ github.event.inputs.environment }}.tfvars | awk -F'"' '{print $2}')

          echo "Syncing kubeconfig for cluster: $CLUSTER_NAME"
          aws eks update-kubeconfig --name $CLUSTER_NAME --region ${{ env.AWS_REGION }}

          echo "Applying StorageClass manifest..."
          kubectl apply -f ./cluster-configs/storageclass.yaml
