name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        options:
        - dev-uat
        - prod

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  terraform-destroy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: github-run-id-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          cd ecr && terraform init && terraform workspace select -or-create ${{ github.event.inputs.environment }}
          cd ../eks && terraform init && terraform workspace select -or-create ${{ github.event.inputs.environment }}

      - name: Destroy EKS
        working-directory: ./eks
        run: |
          terraform plan -destroy -var-file=env/${{ github.event.inputs.environment }}.tfvars
          terraform destroy -var-file=env/${{ github.event.inputs.environment }}.tfvars --auto-approve

      - name: Destroy ECR
        working-directory: ./ecr
        run: |
          terraform plan -destroy -var-file=env/${{ github.event.inputs.environment }}.tfvars
          terraform destroy -var-file=env/${{ github.event.inputs.environment }}.tfvars --auto-approve
