name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        options:
        - dev
        - uat
        - prod

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-1

jobs:
  terraform-destroy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: github-run-id-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init and Capture Output
        run: |
          cd vpc && terraform init && terraform workspace select -or-create ${{ github.event.inputs.environment }}
          echo "VPC_ID=$(terraform output -raw vpc_id)" >> $GITHUB_ENV
          cd ../ecr && terraform init && terraform workspace select -or-create ${{ github.event.inputs.environment }}
          cd ../eks && terraform init && terraform workspace select -or-create ${{ github.event.inputs.environment }}
          echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> $GITHUB_ENV
          cd ../k8s && terraform init && terraform workspace select -or-create ${{ github.event.inputs.environment }}

      - name: Destroy Kubernetes Resources
        working-directory: ./k8s
        env:
          TF_VAR_region: ${{ env.AWS_REGION }}
          TF_VAR_cluster_name: ${{ env.CLUSTER_NAME }}
        run: | 
          terraform plan -destroy
          terraform destroy --auto-approve

      - name: Destroy EKS
        working-directory: ./eks
        env:
          TF_VAR_vpc_id: ${{ env.VPC_ID }}
        run: |
          terraform plan -destroy -var-file=${{ github.event.inputs.environment }}.tfvars
          terraform destroy -var-file=${{ github.event.inputs.environment }}.tfvars --auto-approve

      - name: Destroy ECR
        working-directory: ./ecr
        run: |
          terraform plan -destroy
          terraform destroy --auto-approve

      - name: Destroy VPC
        working-directory: ./vpc
        run: |
          terraform plan -var-file=${{ github.event.inputs.environment }}.tfvars
          terraform destroy -var-file=${{ github.event.inputs.environment }}.tfvars --auto-approve
