name: Terraform CI

on:
  pull_request:
    paths:
      - 'vpc/**'
      - 'ecr/**'
      - 'eks/**'
      - 'k8s/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-vpc:
    uses: ./.github/workflows/Terraform-Check.yaml
    with:
      working_directory: 'vpc'

  check-ecr:
    uses: ./.github/workflows/Terraform-Check.yaml
    with:
      working_directory: 'ecr'

  check-eks:
    uses: ./.github/workflows/Terraform-Check.yaml
    with:
      working_directory: 'eks'

  check-kubernetes:
    uses: ./.github/workflows/Terraform-Check.yaml
    with:
      working_directory: 'k8s'