name: Terraform CI

on:
  pull_request:
    paths:
      - 'ecr/**'
      - 'eks/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  check-ecr:
    uses: ./.github/workflows/Terraform-Check.yaml
    with:
      working_directory: 'ecr'
      region: ${{ vars.AWS_REGION }}
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

  check-eks:
    uses: ./.github/workflows/Terraform-Check.yaml
    with:
      working_directory: 'eks'
      region: ${{ vars.AWS_REGION }}
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}